# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messagebroker.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13messagebroker.proto\x12\rmessagebroker\x1a\x1bgoogle/protobuf/empty.proto\"-\n\x07Message\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\t\"?\n\x05Topic\x12\x0c\n\x04name\x18\x01 \x01(\t\x12(\n\x08messages\x18\x02 \x03(\x0b\x32\x16.messagebroker.Message\"H\n\x0ePublishRequest\x12\r\n\x05topic\x18\x01 \x01(\t\x12\'\n\x07message\x18\x02 \x01(\x0b\x32\x16.messagebroker.Message\"!\n\x10SubscribeRequest\x12\r\n\x05topic\x18\x01 \x01(\t\"<\n\x11SubscribeResponse\x12\'\n\x07message\x18\x01 \x01(\x0b\x32\x16.messagebroker.Message\"\x1e\n\x0b\x41\x63knowledge\x12\x0f\n\x07success\x18\x01 \x01(\x08\"$\n\x12ListTopicsResponse\x12\x0e\n\x06topics\x18\x01 \x03(\t\"I\n\x0fSubscribedTopic\x12\x0c\n\x04name\x18\x01 \x01(\t\x12(\n\x08messages\x18\x02 \x03(\x0b\x32\x16.messagebroker.Message\"M\n\x1bGetSubscribedTopicsResponse\x12.\n\x06topics\x18\x01 \x03(\x0b\x32\x1e.messagebroker.SubscribedTopic2\xcb\x02\n\rMessageBroker\x12\x44\n\x07Publish\x12\x1d.messagebroker.PublishRequest\x1a\x1a.messagebroker.Acknowledge\x12P\n\tSubscribe\x12\x1f.messagebroker.SubscribeRequest\x1a .messagebroker.SubscribeResponse0\x01\x12G\n\nListTopics\x12\x16.google.protobuf.Empty\x1a!.messagebroker.ListTopicsResponse\x12Y\n\x13GetSubscribedTopics\x12\x16.google.protobuf.Empty\x1a*.messagebroker.GetSubscribedTopicsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'messagebroker_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MESSAGE']._serialized_start=67
  _globals['_MESSAGE']._serialized_end=112
  _globals['_TOPIC']._serialized_start=114
  _globals['_TOPIC']._serialized_end=177
  _globals['_PUBLISHREQUEST']._serialized_start=179
  _globals['_PUBLISHREQUEST']._serialized_end=251
  _globals['_SUBSCRIBEREQUEST']._serialized_start=253
  _globals['_SUBSCRIBEREQUEST']._serialized_end=286
  _globals['_SUBSCRIBERESPONSE']._serialized_start=288
  _globals['_SUBSCRIBERESPONSE']._serialized_end=348
  _globals['_ACKNOWLEDGE']._serialized_start=350
  _globals['_ACKNOWLEDGE']._serialized_end=380
  _globals['_LISTTOPICSRESPONSE']._serialized_start=382
  _globals['_LISTTOPICSRESPONSE']._serialized_end=418
  _globals['_SUBSCRIBEDTOPIC']._serialized_start=420
  _globals['_SUBSCRIBEDTOPIC']._serialized_end=493
  _globals['_GETSUBSCRIBEDTOPICSRESPONSE']._serialized_start=495
  _globals['_GETSUBSCRIBEDTOPICSRESPONSE']._serialized_end=572
  _globals['_MESSAGEBROKER']._serialized_start=575
  _globals['_MESSAGEBROKER']._serialized_end=906
# @@protoc_insertion_point(module_scope)
