# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messagebroker.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13messagebroker.proto\x12\rmessagebroker\x1a\x1bgoogle/protobuf/empty.proto\"5\n\x07Mensaje\x12\x11\n\tcontenido\x18\x01 \x01(\t\x12\x17\n\x0fmarca_de_tiempo\x18\x02 \x01(\t\"@\n\x04Tema\x12\x0e\n\x06nombre\x18\x01 \x01(\t\x12(\n\x08mensajes\x18\x02 \x03(\x0b\x32\x16.messagebroker.Mensaje\"J\n\x11PublicarSolicitud\x12\x0c\n\x04tema\x18\x01 \x01(\t\x12\'\n\x07mensaje\x18\x02 \x01(\x0b\x32\x16.messagebroker.Mensaje\"\"\n\x12SuscribirSolicitud\x12\x0c\n\x04tema\x18\x01 \x01(\t\"=\n\x12SuscribirRespuesta\x12\'\n\x07mensaje\x18\x01 \x01(\x0b\x32\x16.messagebroker.Mensaje\"\x1c\n\x0b\x41\x63knowledge\x12\r\n\x05\x65xito\x18\x01 \x01(\x08\"%\n\x14ListarTemasRespuesta\x12\r\n\x05temas\x18\x01 \x03(\t\"H\n\x0cTemaSuscrito\x12\x0e\n\x06nombre\x18\x01 \x01(\t\x12(\n\x08mensajes\x18\x02 \x03(\x0b\x32\x16.messagebroker.Mensaje\"L\n\x1eObtenerTemasSuscritosRespuesta\x12*\n\x05temas\x18\x01 \x03(\x0b\x32\x1b.messagebroker.TemaSuscrito2\xda\x02\n\rMessageBroker\x12H\n\x08Publicar\x12 .messagebroker.PublicarSolicitud\x1a\x1a.messagebroker.Acknowledge\x12S\n\tSuscribir\x12!.messagebroker.SuscribirSolicitud\x1a!.messagebroker.SuscribirRespuesta0\x01\x12J\n\x0bListarTemas\x12\x16.google.protobuf.Empty\x1a#.messagebroker.ListarTemasRespuesta\x12^\n\x15ObtenerTemasSuscritos\x12\x16.google.protobuf.Empty\x1a-.messagebroker.ObtenerTemasSuscritosRespuestab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'messagebroker_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MENSAJE']._serialized_start=67
  _globals['_MENSAJE']._serialized_end=120
  _globals['_TEMA']._serialized_start=122
  _globals['_TEMA']._serialized_end=186
  _globals['_PUBLICARSOLICITUD']._serialized_start=188
  _globals['_PUBLICARSOLICITUD']._serialized_end=262
  _globals['_SUSCRIBIRSOLICITUD']._serialized_start=264
  _globals['_SUSCRIBIRSOLICITUD']._serialized_end=298
  _globals['_SUSCRIBIRRESPUESTA']._serialized_start=300
  _globals['_SUSCRIBIRRESPUESTA']._serialized_end=361
  _globals['_ACKNOWLEDGE']._serialized_start=363
  _globals['_ACKNOWLEDGE']._serialized_end=391
  _globals['_LISTARTEMASRESPUESTA']._serialized_start=393
  _globals['_LISTARTEMASRESPUESTA']._serialized_end=430
  _globals['_TEMASUSCRITO']._serialized_start=432
  _globals['_TEMASUSCRITO']._serialized_end=504
  _globals['_OBTENERTEMASSUSCRITOSRESPUESTA']._serialized_start=506
  _globals['_OBTENERTEMASSUSCRITOSRESPUESTA']._serialized_end=582
  _globals['_MESSAGEBROKER']._serialized_start=585
  _globals['_MESSAGEBROKER']._serialized_end=931
# @@protoc_insertion_point(module_scope)
