# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import messagebroker_pb2 as messagebroker__pb2

GRPC_GENERATED_VERSION = '1.63.0'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in messagebroker_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class MessageBrokerStub(object):
    """Definicion de los servicios
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Publicar = channel.unary_unary(
                '/messagebroker.MessageBroker/Publicar',
                request_serializer=messagebroker__pb2.PublicarSolicitud.SerializeToString,
                response_deserializer=messagebroker__pb2.Acknowledge.FromString,
                _registered_method=True)
        self.Suscribir = channel.unary_stream(
                '/messagebroker.MessageBroker/Suscribir',
                request_serializer=messagebroker__pb2.SuscribirSolicitud.SerializeToString,
                response_deserializer=messagebroker__pb2.SuscribirRespuesta.FromString,
                _registered_method=True)
        self.ListarTemas = channel.unary_unary(
                '/messagebroker.MessageBroker/ListarTemas',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=messagebroker__pb2.ListarTemasRespuesta.FromString,
                _registered_method=True)
        self.ObtenerTemasSuscritos = channel.unary_unary(
                '/messagebroker.MessageBroker/ObtenerTemasSuscritos',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=messagebroker__pb2.ObtenerTemasSuscritosRespuesta.FromString,
                _registered_method=True)


class MessageBrokerServicer(object):
    """Definicion de los servicios
    """

    def Publicar(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Suscribir(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListarTemas(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ObtenerTemasSuscritos(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MessageBrokerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Publicar': grpc.unary_unary_rpc_method_handler(
                    servicer.Publicar,
                    request_deserializer=messagebroker__pb2.PublicarSolicitud.FromString,
                    response_serializer=messagebroker__pb2.Acknowledge.SerializeToString,
            ),
            'Suscribir': grpc.unary_stream_rpc_method_handler(
                    servicer.Suscribir,
                    request_deserializer=messagebroker__pb2.SuscribirSolicitud.FromString,
                    response_serializer=messagebroker__pb2.SuscribirRespuesta.SerializeToString,
            ),
            'ListarTemas': grpc.unary_unary_rpc_method_handler(
                    servicer.ListarTemas,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=messagebroker__pb2.ListarTemasRespuesta.SerializeToString,
            ),
            'ObtenerTemasSuscritos': grpc.unary_unary_rpc_method_handler(
                    servicer.ObtenerTemasSuscritos,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=messagebroker__pb2.ObtenerTemasSuscritosRespuesta.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'messagebroker.MessageBroker', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MessageBroker(object):
    """Definicion de los servicios
    """

    @staticmethod
    def Publicar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/messagebroker.MessageBroker/Publicar',
            messagebroker__pb2.PublicarSolicitud.SerializeToString,
            messagebroker__pb2.Acknowledge.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Suscribir(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/messagebroker.MessageBroker/Suscribir',
            messagebroker__pb2.SuscribirSolicitud.SerializeToString,
            messagebroker__pb2.SuscribirRespuesta.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListarTemas(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/messagebroker.MessageBroker/ListarTemas',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            messagebroker__pb2.ListarTemasRespuesta.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ObtenerTemasSuscritos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/messagebroker.MessageBroker/ObtenerTemasSuscritos',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            messagebroker__pb2.ObtenerTemasSuscritosRespuesta.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
